[program:ids_dashboard]
command=cd /Users/chandankumarsah/itrix_ai_ids/backend && gunicorn -w 4 -b 0.0.0.0:5001 app:app
directory=/Users/chandankumarsah/itrix_ai_ids
autostart=true
autorestart=true
stderr_logfile=/Users/chandankumarsah/itrix_ai_ids/supervisor_err.log
stdout_logfile=/Users/chandankumarsah/itrix_ai_ids/supervisor_out.log

[program:ids_watcher]
command=cd /Users/chandankumarsah/itrix_ai_ids && python3 auto_detect.py
directory=/Users/chandankumarsah/itrix_ai_ids
autostart=true
autorestart=true
stderr_logfile=/Users/chandankumarsah/itrix_ai_ids/watcher_err.log
stdout_logfile=/Users/chandankumarsah/itrix_ai_ids/watcher_out.log

[program:ids_capture]
command=cd /Users/chandankumarsah/itrix_ai_ids && python3 live_capture.py
directory=/Users/chandankumarsah/itrix_ai_ids
autostart=true
autorestart=true
stderr_logfile=/Users/chandankumarsah/itrix_ai_ids/live_err.log
stdout_logfile=/Users/chandankumarsah/itrix_ai_ids/live_out.log
